name: Test

on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          check-latest: true

      - name: Printing node version
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm i

      - name: Run test:codestyle
        run: npm run test:codestyle